from pathlib import Path

from .paths import safe_project_path


PYTORCH_DIRECTORIES = [
    "src",
    "src/models",
    "src/data",
    "src/training",
    "configs",
    "tests",
    "outputs"
]


def create_directories(
    root: Path,
    directories: list[str]
) -> list[str]:
    """
    Create project directories.

    Returns paths relative to project root.
    """

    created = []

    for directory in directories:

        path = root / directory

        path.mkdir(
            parents=True,
            exist_ok=True
        )

        created.append(
            directory
        )

    return created


def create_readme(
    root: Path,
    project_name: str,
    framework: str,
    task_type: str
) -> str:

    content = f"""# {project_name}

Generated by PaperForge.

## Framework

{framework}

## Task Type

{task_type}
"""

    readme_path = (
        root
        / "README.md"
    )

    readme_path.write_text(
        content,
        encoding="utf-8"
    )

    return "README.md"


def initialize_project(
    project_name: str,
    framework: str = "pytorch",
    task_type: str = "deep_learning"
) -> dict:
    """
    Initialize a safe implementation workspace.
    """

    project_root = safe_project_path(
        project_name
    )

    already_exists = (
        project_root.exists()
    )

    project_root.mkdir(
        parents=True,
        exist_ok=True
    )

    framework_normalized = (
        framework
        .strip()
        .lower()
    )

    if framework_normalized == "pytorch":

        directories = (
            PYTORCH_DIRECTORIES
        )

    else:
        directories = [
            "src",
            "configs",
            "tests",
            "outputs"
        ]

    created_directories = (
        create_directories(
            root=project_root,
            directories=directories
        )
    )

    readme = create_readme(
        root=project_root,
        project_name=project_name,
        framework=framework,
        task_type=task_type
    )

    return {
        "status": "success",

        "project": {
            "name": project_name,
            "framework": framework,
            "task_type": task_type,
            "already_existed": already_exists
        },

        "created_directories":
            created_directories,

        "created_files": [
            readme
        ]
    }